-- MySQL Script generated by MySQL Workbench
-- Fri Jun 19 13:28:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema id14070139_notas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id14070139_notas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id14070139_notas` DEFAULT CHARACTER SET utf8 ;
USE `id14070139_notas` ;

-- -----------------------------------------------------
-- Table `id14070139_notas`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id14070139_notas`.`notas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nota` TEXT(255) NOT NULL,
  `titulo` VARCHAR(20) NOT NULL,
  `data` DATETIME NOT NULL,
  `cor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
